version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  build:
    commands:
      - echo Building Docker image...
      - docker build -t myapp .
      - docker tag myapp $DOCKER_USERNAME/myapp:latest
      - docker push $DOCKER_USERNAME/myapp:latest
artifacts:
  files:
    - appspec.yml
    - scripts/*
