name: Container CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-container-app .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-container-app

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/ci-cd-container-app
          docker stop ci-cd-app || true
          docker rm ci-cd-app || true
          docker run -d --name ci-cd-app -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/ci-cd-container-app

